/**
 * Pilots DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: pilots
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Pilots Domain Module - Composition root
 *
 * DDD: Composition root for pilots domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  AuditPackRepositoryAdapter,
  CharterRepositoryAdapter,
  DecisionRepositoryAdapter,
  PilotRepositoryAdapter,
} from "@pilotspan/adapters/pilots";
import { getIdGeneratorService } from "@pilotspan/adapters";
import type { AdapterDynamoDBClient } from "@pilotspan/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreatePilot,
  ExecuteGetGraduateAuditPack,
  ExecuteGetPilot,
  ExecuteGetPilotCharter,
  ExecuteListPilotDecisions,
  ExecuteListPilots,
  ExecuteRecordPortfolioDecision,
  ExecuteUpsertPilotCharter,
} from "@pilotspan/services/pilots/usecases";
// Ports (interfaces)
import type {
  AuditPackRepository,
  CharterRepository,
  DecisionRepository,
  PilotRepository,
} from "@pilotspan/services/pilots/ports";

export interface PilotsDomainModule {
  repos: {
    auditPacks: AuditPackRepository;
    charters: CharterRepository;
    decisions: DecisionRepository;
    pilots: PilotRepository;
  };
  useCases: {
    auditPacks: {
      get: ExecuteGetGraduateAuditPack;
    };
    charters: {
      get: ExecuteUpsertPilotCharter;
    };
    decisions: {
      get: ExecuteRecordPortfolioDecision;
      list: ExecuteListPilotDecisions;
    };
    pilots: {
      create: ExecuteCreatePilot;
      get: ExecuteGetPilot;
      list: ExecuteListPilots;
    };
  };
}

export function buildPilotsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): PilotsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      auditPacks?: AuditPackRepository;
      charters?: CharterRepository;
      decisions?: DecisionRepository;
      pilots?: PilotRepository;
    } = {};

    obj.auditPacks = new AuditPackRepositoryAdapter(dynamoClient);
    obj.charters = new CharterRepositoryAdapter(dynamoClient);
    obj.decisions = new DecisionRepositoryAdapter(dynamoClient);
    obj.pilots = new PilotRepositoryAdapter(dynamoClient);
    return {
      auditPacks: obj.auditPacks!,
      charters: obj.charters!,
      decisions: obj.decisions!,
      pilots: obj.pilots!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    auditPacks: {
      get: new ExecuteGetGraduateAuditPack(executionContext, idGenerator, repos.auditPacks),
    },
    charters: {
      get: new ExecuteUpsertPilotCharter(executionContext, idGenerator, repos.charters),
    },
    decisions: {
      get: new ExecuteRecordPortfolioDecision(executionContext, idGenerator, repos.decisions),
      list: new ExecuteListPilotDecisions(executionContext, idGenerator, repos.decisions),
    },
    pilots: {
      create: new ExecuteCreatePilot(executionContext, idGenerator, repos.pilots),
      get: new ExecuteGetPilot(executionContext, idGenerator, repos.pilots),
      list: new ExecuteListPilots(executionContext, idGenerator, repos.pilots),
    },
  };
  return { repos, useCases: useCases as PilotsDomainModule["useCases"] };
}
