/**
 * DynamoDB repository adapters barrel export
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: shadow-ai
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./remediation-repository.ddb.js";
export * from "./shadow-ai-system-repository.ddb.js";
export * from "./remediation-repository.adapter.js";
export * from "./shadow-ai-system-repository.adapter.js";
