/**
 * ShadowAiSystemRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: shadow-ai
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ShadowAiSystemRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ShadowAiSystemRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ShadowAiSystemRepository,
} from "@pilotspan/services/shadow-ai";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ShadowAiSystemRepositoryDdb } from "./shadow-ai-system-repository.ddb.js";

/**
 * ShadowAiSystemRepositoryAdapter
 *
 * Implements ShadowAiSystemRepository port for infrastructure layer.
 */
export class ShadowAiSystemRepositoryAdapter implements ShadowAiSystemRepository {
  private readonly ddb: ShadowAiSystemRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ShadowAiSystemRepositoryDdb(this.dynamoClient);
  }

  async listShadowAiSystems(input: Parameters<ShadowAiSystemRepository['listShadowAiSystems']>[0]): Promise<Awaited<ReturnType<ShadowAiSystemRepository['listShadowAiSystems']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listShadowAiSystems(input);
  }

  async createShadowAiSystem(input: Parameters<ShadowAiSystemRepository['createShadowAiSystem']>[0]): Promise<Awaited<ReturnType<ShadowAiSystemRepository['createShadowAiSystem']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createShadowAiSystem(input);
  }

  async getShadowAiSystem(input: Parameters<ShadowAiSystemRepository['getShadowAiSystem']>[0]): Promise<Awaited<ReturnType<ShadowAiSystemRepository['getShadowAiSystem']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getShadowAiSystem(input);
  }
}
