/**
 * Handlers for Decision
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: anonymisation-gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { AnonymisationGatesDomainModule } from "../dependencies/anonymisation-gates-ddd.dependencies.js";
import type { DecideAnonymisationGateInput } from "@pilotspan/services/anonymisation-gates";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/anonymisation-gates/{gateId}/decision
 * Operation: decideAnonymisationGate
 */
export async function decideAnonymisationGate(
  request: FastifyRequest<{ Params: { gateId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: AnonymisationGatesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: DecideAnonymisationGateInput = {
    gateId: request.params.gateId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.decisions.get.execute(input);
  return reply.code(200).send(result);
}


