/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: shadow-ai
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { remediationRoutes } from "./remediation.routes.js";
export { shadowAiSystemRoutes } from "./shadow-ai-system.routes.js";
