/**
 * Routes for ShadowAiSystem
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: shadow-ai
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createShadowAiSystem, getShadowAiSystem, listShadowAiSystems } from "../handlers/shadow-ai-system.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function shadowAiSystemRoutes(fastify: FastifyInstance) {
  // POST /v1/shadow-ai-systems (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/shadow-ai-systems",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getShadowAiDependenciesForRequest();
        await createShadowAiSystem(request, reply, deps);
      });
    }
  );


  // GET /v1/shadow-ai-systems (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/shadow-ai-systems",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getShadowAiDependenciesForRequest();
        await listShadowAiSystems(request, reply, deps);
      });
    }
  );


  // GET /v1/shadow-ai-systems/{systemId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/shadow-ai-systems/:systemId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { systemId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getShadowAiDependenciesForRequest();
        await getShadowAiSystem(request, reply, deps);
      });
    }
  );


}
