/**
 * Dependency Container
 *
 * AUTO-GENERATED by codegen (api_server_domain_dependencies). Do not edit by hand.
 * Regenerate with: pnpm run codegen (domain list from platform/api-server/src/domains rescan).
 *
 * Manages dependency creation and caching per domain.
 */

import type { AdapterDynamoDBClient } from "@pilotspan/adapters";
import { getDynamoClientInstance } from "../lib/dependencies/domain-dependencies.js";
import { executionContextService } from "../lib/context/execution-context.service.js";
import {
  buildAnonymisationGatesDomainModule,
  buildCustodiansDomainModule,
  buildIdentityDomainModule,
  buildPilotsDomainModule,
  buildReadinessDomainModule,
  buildShadowAiDomainModule,
  buildTalentAssignmentsDomainModule,
} from "../domains/index.js";
import type {
  AnonymisationGatesDomainModule,
  CustodiansDomainModule,
  IdentityDomainModule,
  PilotsDomainModule,
  ReadinessDomainModule,
  ShadowAiDomainModule,
  TalentAssignmentsDomainModule,
} from "../domains/index.js";

class DependencyContainer {
  private readonly dynamoClient: AdapterDynamoDBClient;

  private anonymisationGatesModule: AnonymisationGatesDomainModule | null = null;
  private custodiansModule: CustodiansDomainModule | null = null;
  private identityModule: IdentityDomainModule | null = null;
  private pilotsModule: PilotsDomainModule | null = null;
  private readinessModule: ReadinessDomainModule | null = null;
  private shadowAiModule: ShadowAiDomainModule | null = null;
  private talentAssignmentsModule: TalentAssignmentsDomainModule | null = null;

  constructor(dynamoClient: AdapterDynamoDBClient) {
    this.dynamoClient = dynamoClient;
  }

  /**
   * Get anonymisation-gates domain module
   */
  getAnonymisationGatesDependencies(): AnonymisationGatesDomainModule {
    if (!this.anonymisationGatesModule) {
      this.anonymisationGatesModule = buildAnonymisationGatesDomainModule(this.dynamoClient);
    }
    return this.anonymisationGatesModule;
  }

  /**
   * Get custodians domain module
   */
  getCustodiansDependencies(): CustodiansDomainModule {
    if (!this.custodiansModule) {
      this.custodiansModule = buildCustodiansDomainModule(this.dynamoClient);
    }
    return this.custodiansModule;
  }

  /**
   * Get identity domain module
   */
  getIdentityDependencies(): IdentityDomainModule {
    if (!this.identityModule) {
      this.identityModule = buildIdentityDomainModule(this.dynamoClient);
    }
    return this.identityModule;
  }

  /**
   * Get pilots domain module
   */
  getPilotsDependencies(): PilotsDomainModule {
    if (!this.pilotsModule) {
      this.pilotsModule = buildPilotsDomainModule(this.dynamoClient);
    }
    return this.pilotsModule;
  }

  /**
   * Get readiness domain module
   */
  getReadinessDependencies(): ReadinessDomainModule {
    if (!this.readinessModule) {
      this.readinessModule = buildReadinessDomainModule(this.dynamoClient);
    }
    return this.readinessModule;
  }

  /**
   * Get shadow-ai domain module
   */
  getShadowAiDependencies(): ShadowAiDomainModule {
    if (!this.shadowAiModule) {
      this.shadowAiModule = buildShadowAiDomainModule(this.dynamoClient);
    }
    return this.shadowAiModule;
  }

  /**
   * Get talent-assignments domain module
   */
  getTalentAssignmentsDependencies(): TalentAssignmentsDomainModule {
    if (!this.talentAssignmentsModule) {
      this.talentAssignmentsModule = buildTalentAssignmentsDomainModule(this.dynamoClient);
    }
    return this.talentAssignmentsModule;
  }

  clearAnonymisationGatesDependencies(): void { this.anonymisationGatesModule = null; }
  clearCustodiansDependencies(): void { this.custodiansModule = null; }
  clearIdentityDependencies(): void { this.identityModule = null; }
  clearPilotsDependencies(): void { this.pilotsModule = null; }
  clearReadinessDependencies(): void { this.readinessModule = null; }
  clearShadowAiDependencies(): void { this.shadowAiModule = null; }
  clearTalentAssignmentsDependencies(): void { this.talentAssignmentsModule = null; }

  getAnonymisationGatesDependenciesForRequest(): AnonymisationGatesDomainModule {
    return this.getAnonymisationGatesDependencies();
  }

  getCustodiansDependenciesForRequest(): CustodiansDomainModule {
    return this.getCustodiansDependencies();
  }

  getIdentityDependenciesForRequest(): IdentityDomainModule {
    return this.getIdentityDependencies();
  }

  getPilotsDependenciesForRequest(): PilotsDomainModule {
    return this.getPilotsDependencies();
  }

  getReadinessDependenciesForRequest(): ReadinessDomainModule {
    return this.getReadinessDependencies();
  }

  getShadowAiDependenciesForRequest(): ShadowAiDomainModule {
    return this.getShadowAiDependencies();
  }

  getTalentAssignmentsDependenciesForRequest(): TalentAssignmentsDomainModule {
    return this.getTalentAssignmentsDependencies();
  }

  /**
   * Clear all caches
   */
  clearAllCaches(): void {
    this.anonymisationGatesModule = null;
    this.custodiansModule = null;
    this.identityModule = null;
    this.pilotsModule = null;
    this.readinessModule = null;
    this.shadowAiModule = null;
    this.talentAssignmentsModule = null;
  }
}

let dependencyContainerInstance: DependencyContainer | null = null;

export function getDependencyContainer(): DependencyContainer {
  if (!dependencyContainerInstance) {
    const dynamoClient = getDynamoClientInstance();
    dependencyContainerInstance = new DependencyContainer(dynamoClient);
  }
  return dependencyContainerInstance;
}
