/**
 * Handlers for Remediation
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: shadow-ai
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ShadowAiDomainModule } from "../dependencies/shadow-ai-ddd.dependencies.js";
import type { RemediateShadowAiSystemInput } from "@pilotspan/services/shadow-ai";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/shadow-ai-systems/{systemId}/remediation
 * Operation: remediateShadowAiSystem
 */
export async function remediateShadowAiSystem(
  request: FastifyRequest<{ Params: { systemId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ShadowAiDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: RemediateShadowAiSystemInput = {
    systemId: request.params.systemId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.remediations.get.execute(input);
  return reply.code(200).send(result);
}


