/**
 * Handlers for ShadowAiSystem
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: shadow-ai
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ShadowAiDomainModule } from "../dependencies/shadow-ai-ddd.dependencies.js";
import type { CreateShadowAiSystemInput, GetShadowAiSystemInput, ListShadowAiSystemsInput } from "@pilotspan/services/shadow-ai";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/shadow-ai-systems
 * Operation: listShadowAiSystems
 */
export async function listShadowAiSystems(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], status?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: ShadowAiDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListShadowAiSystemsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.systems.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/shadow-ai-systems
 * Operation: createShadowAiSystem
 */
export async function createShadowAiSystem(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: ShadowAiDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateShadowAiSystemInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.systems.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/shadow-ai-systems/{systemId}
 * Operation: getShadowAiSystem
 */
export async function getShadowAiSystem(
  request: FastifyRequest<{ Params: { systemId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ShadowAiDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetShadowAiSystemInput = {
    systemId: request.params.systemId,
  };
  const result = await deps.useCases.systems.get.execute(input);
  return reply.code(200).send(result);
}


