/**
 * ExecuteGetPilotCharter - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: pilots
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetPilotCharter Use Case
 *
 * DDD: Application use case for get Charter.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetPilotCharterInput, GetPilotCharterOutput } from "../dto/charter.dto";
import type { ExecutionContextService, IdGeneratorService } from "@pilotspan/services/_shared/index.js";
import type { CharterRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetPilotCharter {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly charter: CharterRepository
  ) {}

  async execute(input: GetPilotCharterInput): Promise<GetPilotCharterOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.pltId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).pilotId) {
      throw new ValidationError("pilotId is required");
    }
    const pilotId = (input as any).pilotId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.charter.getPilotCharter({ pilotId: pilotId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${pilotId}`);
    }

    return entity as GetPilotCharterOutput;
  }
}
