/**
 * ListTalentAssignment DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: talent-assignments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListTalentAssignmentsParams } from "@pilotspan/core/talent-assignments";

export function createListTalentAssignmentRequest(overrides: Partial<ListTalentAssignmentsParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
