/**
 * Routes for Custodian
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: custodians
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { assignCustodian, listCustodians } from "../handlers/custodian.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function custodianRoutes(fastify: FastifyInstance) {
  // POST /v1/custodians (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/custodians",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getCustodiansDependenciesForRequest();
        await assignCustodian(request, reply, deps);
      });
    }
  );


  // GET /v1/custodians (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/custodians",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getCustodiansDependenciesForRequest();
        await listCustodians(request, reply, deps);
      });
    }
  );


}
