/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: custodians
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { custodianRoutes } from "./custodian.routes.js";
export { datasetApprovalRoutes } from "./dataset-approval.routes.js";
export { qualityIssueRoutes } from "./quality-issue.routes.js";
