/**
 * AuditPack DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: pilots
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AuditPack DTOs
 *
 * DDD: Application DTOs for AuditPack use cases.
 */

import type { GetGraduateAuditPackParams } from "@pilotspan/core/pilots/types";

export type GetGraduateAuditPackInput = GetGraduateAuditPackParams;

export type GetGraduateAuditPackOutput = {};
