/**
 * AdmissionRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: readiness
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AdmissionRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements AdmissionRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  AdmissionRepository,
} from "@pilotspan/services/readiness";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { AdmissionRepositoryDdb } from "./admission-repository.ddb.js";

/**
 * AdmissionRepositoryAdapter
 *
 * Implements AdmissionRepository port for infrastructure layer.
 */
export class AdmissionRepositoryAdapter implements AdmissionRepository {
  private readonly ddb: AdmissionRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new AdmissionRepositoryDdb(this.dynamoClient);
  }

  async decideReadinessAdmission(input: Parameters<AdmissionRepository['decideReadinessAdmission']>[0]): Promise<Awaited<ReturnType<AdmissionRepository['decideReadinessAdmission']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.decideReadinessAdmission(input);
  }
}
