/**
 * ReadinessAssessmentRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: readiness
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ReadinessAssessmentRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ReadinessAssessmentRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ReadinessAssessmentRepository,
} from "@pilotspan/services/readiness";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ReadinessAssessmentRepositoryDdb } from "./readiness-assessment-repository.ddb.js";

/**
 * ReadinessAssessmentRepositoryAdapter
 *
 * Implements ReadinessAssessmentRepository port for infrastructure layer.
 */
export class ReadinessAssessmentRepositoryAdapter implements ReadinessAssessmentRepository {
  private readonly ddb: ReadinessAssessmentRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ReadinessAssessmentRepositoryDdb(this.dynamoClient);
  }

  async listReadinessAssessments(input: Parameters<ReadinessAssessmentRepository['listReadinessAssessments']>[0]): Promise<Awaited<ReturnType<ReadinessAssessmentRepository['listReadinessAssessments']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listReadinessAssessments(input);
  }

  async createReadinessAssessment(input: Parameters<ReadinessAssessmentRepository['createReadinessAssessment']>[0]): Promise<Awaited<ReturnType<ReadinessAssessmentRepository['createReadinessAssessment']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createReadinessAssessment(input);
  }

  async getReadinessAssessment(input: Parameters<ReadinessAssessmentRepository['getReadinessAssessment']>[0]): Promise<Awaited<ReturnType<ReadinessAssessmentRepository['getReadinessAssessment']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getReadinessAssessment(input);
  }
}
