/**
 * GetShadowAiSystem handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: shadow-ai
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getShadowAiSystem } from "@pilotspan/api-server/domains/shadow-ai/handlers";
import type { ShadowAiDDDDependencies } from "@pilotspan/api-server/domains/shadow-ai";
import { createShadowAiSystem as createShadowAiSystemEntity } from "@pilotspan/factories/shadow-ai";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@pilotspan/tests/shared";
import { SHADOWAI_USE_CASES } from "../__factories__/use-cases.js";

describe("GetShadowAiSystem", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ShadowAiDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ShadowAiDDDDependencies>(
      SHADOWAI_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createShadowAiSystemEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetShadowAiSystem, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { systemId: entity.id };

    await getShadowAiSystem(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetShadowAiSystem.execute).toHaveBeenCalledWith(expect.objectContaining({ systemId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { systemId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetShadowAiSystem, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getShadowAiSystem(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
