/**
 * AssignCustodian handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: custodians
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { assignCustodian } from "@pilotspan/api-server/domains/custodians/handlers";
import type { CustodiansDDDDependencies } from "@pilotspan/api-server/domains/custodians";
import { createCustodian as createCustodianEntity } from "@pilotspan/factories/custodians";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@pilotspan/tests/shared";
import { CUSTODIANS_USE_CASES } from "../__factories__/use-cases.js";

describe("AssignCustodian", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: CustodiansDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<CustodiansDDDDependencies>(
      CUSTODIANS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = createCustodianEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeAssignCustodian, "execute").mockResolvedValue(useCaseResult);

    await assignCustodian(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeAssignCustodian.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
