/**
 * Repository interface for AnonymisationGate
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: anonymisation-gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  AnonymisationGateEntity
} from "../models/anonymisation-gate.entity.js";
import type {
  ListAnonymisationGatesParams,
  AnonymisationGate
} from "../types/index.js";
/**
 * AnonymisationGateRepository Interface
 */
export interface AnonymisationGateRepository extends CreateReadRepository<AnonymisationGateEntity, AnonymisationGate, string, ListAnonymisationGatesParams> {

}
