/**
 * ShadowAi DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: shadow-ai
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ShadowAi Domain Module - Composition root
 *
 * DDD: Composition root for shadow-ai domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  RemediationRepositoryAdapter,
  ShadowAiSystemRepositoryAdapter,
} from "@pilotspan/adapters/shadow-ai";
import { getIdGeneratorService } from "@pilotspan/adapters";
import type { AdapterDynamoDBClient } from "@pilotspan/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateShadowAiSystem,
  ExecuteGetShadowAiSystem,
  ExecuteListShadowAiSystems,
  ExecuteRemediateShadowAiSystem,
} from "@pilotspan/services/shadow-ai/usecases";
// Ports (interfaces)
import type {
  RemediationRepository,
  ShadowAiSystemRepository,
} from "@pilotspan/services/shadow-ai/ports";

export interface ShadowAiDomainModule {
  repos: {
    remediations: RemediationRepository;
    systems: ShadowAiSystemRepository;
  };
  useCases: {
    remediations: {
      get: ExecuteRemediateShadowAiSystem;
    };
    systems: {
      create: ExecuteCreateShadowAiSystem;
      get: ExecuteGetShadowAiSystem;
      list: ExecuteListShadowAiSystems;
    };
  };
}

export function buildShadowAiDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): ShadowAiDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      remediations?: RemediationRepository;
      systems?: ShadowAiSystemRepository;
    } = {};

    obj.remediations = new RemediationRepositoryAdapter(dynamoClient);
    obj.systems = new ShadowAiSystemRepositoryAdapter(dynamoClient);
    return {
      remediations: obj.remediations!,
      systems: obj.systems!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    remediations: {
      get: new ExecuteRemediateShadowAiSystem(executionContext, idGenerator, repos.remediations),
    },
    systems: {
      create: new ExecuteCreateShadowAiSystem(executionContext, idGenerator, repos.systems),
      get: new ExecuteGetShadowAiSystem(executionContext, idGenerator, repos.systems),
      list: new ExecuteListShadowAiSystems(executionContext, idGenerator, repos.systems),
    },
  };
  return { repos, useCases: useCases as ShadowAiDomainModule["useCases"] };
}
