/**
 * RemediateShadowAiSystem handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: shadow-ai
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { remediateShadowAiSystem } from "@pilotspan/api-server/domains/shadow-ai/handlers";
import type { ShadowAiDDDDependencies } from "@pilotspan/api-server/domains/shadow-ai";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@pilotspan/tests/shared";
import { SHADOWAI_USE_CASES } from "../__factories__/use-cases.js";

describe("RemediateShadowAiSystem", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ShadowAiDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ShadowAiDDDDependencies>(
      SHADOWAI_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeRemediateShadowAiSystem, "execute").mockResolvedValue(useCaseResult);

    await remediateShadowAiSystem(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeRemediateShadowAiSystem.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
