/**
 * Repository interface for Custodian
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: custodians
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  CustodianEntity
} from "../models/custodian.entity.js";
import type {
  ListCustodiansParams,
  Custodian
} from "../types/index.js";
/**
 * CustodianRepository Interface
 */
export interface CustodianRepository extends CreateReadRepository<CustodianEntity, Custodian, string, ListCustodiansParams> {

}
