/**
 * Repository interface for ShadowAiSystem
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: shadow-ai
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  ShadowAiSystemEntity
} from "../models/shadow-ai-system.entity.js";
import type {
  ListShadowAiSystemsParams,
  ShadowAiSystem
} from "../types/index.js";
/**
 * ShadowAiSystemRepository Interface
 */
export interface ShadowAiSystemRepository extends CreateReadRepository<ShadowAiSystemEntity, ShadowAiSystem, string, ListShadowAiSystemsParams> {

}
