/**
 * CreateTalentAssignment handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: talent-assignments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { createTalentAssignment } from "@pilotspan/api-server/domains/talent-assignments/handlers";
import type { TalentAssignmentsDDDDependencies } from "@pilotspan/api-server/domains/talent-assignments";
import { createTalentAssignment as createTalentAssignmentEntity } from "@pilotspan/factories/talent-assignments";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@pilotspan/tests/shared";
import { TALENTASSIGNMENTS_USE_CASES } from "../__factories__/use-cases.js";

describe("CreateTalentAssignment", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: TalentAssignmentsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<TalentAssignmentsDDDDependencies>(
      TALENTASSIGNMENTS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = createTalentAssignmentEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeCreateTalentAssignment, "execute").mockResolvedValue(useCaseResult);

    await createTalentAssignment(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeCreateTalentAssignment.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
