/**
 * ListTalentAssignments handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: talent-assignments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listTalentAssignments } from "@pilotspan/api-server/domains/talent-assignments/handlers";
import type { TalentAssignmentsDDDDependencies } from "@pilotspan/api-server/domains/talent-assignments";
import { createTalentAssignment as createTalentAssignmentEntity } from "@pilotspan/factories/talent-assignments";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@pilotspan/tests/shared";
import { TALENTASSIGNMENTS_USE_CASES } from "../__factories__/use-cases.js";

describe("ListTalentAssignments", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: TalentAssignmentsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<TalentAssignmentsDDDDependencies>(
      TALENTASSIGNMENTS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createTalentAssignmentEntity({ orgId }),
      createTalentAssignmentEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListTalentAssignments, "execute").mockResolvedValue(useCaseResult);

    await listTalentAssignments(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListTalentAssignments.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
