/**
 * Handlers for Custodian
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: custodians
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { CustodiansDomainModule } from "../dependencies/custodians-ddd.dependencies.js";
import type { AssignCustodianInput, ListCustodiansInput } from "@pilotspan/services/custodians";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/custodians
 * Operation: listCustodians
 */
export async function listCustodians(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: CustodiansDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListCustodiansInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.custodians.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/custodians
 * Operation: assignCustodian
 */
export async function assignCustodian(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: CustodiansDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: AssignCustodianInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.custodians.get.execute(input);
  return reply.code(201).send(result);
}


