/**
 * ListAnonymisationGates handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: anonymisation-gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listAnonymisationGates } from "@pilotspan/api-server/domains/anonymisation-gates/handlers";
import type { AnonymisationGatesDDDDependencies } from "@pilotspan/api-server/domains/anonymisation-gates";
import { createAnonymisationGate as createAnonymisationGateEntity } from "@pilotspan/factories/anonymisation-gates";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@pilotspan/tests/shared";
import { ANONYMISATIONGATES_USE_CASES } from "../__factories__/use-cases.js";

describe("ListAnonymisationGates", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: AnonymisationGatesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<AnonymisationGatesDDDDependencies>(
      ANONYMISATIONGATES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createAnonymisationGateEntity({ orgId }),
      createAnonymisationGateEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListAnonymisationGates, "execute").mockResolvedValue(useCaseResult);

    await listAnonymisationGates(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListAnonymisationGates.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
