/**
 * SubmitAnonymisationGate handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: anonymisation-gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { submitAnonymisationGate } from "@pilotspan/api-server/domains/anonymisation-gates/handlers";
import type { AnonymisationGatesDDDDependencies } from "@pilotspan/api-server/domains/anonymisation-gates";
import { createAnonymisationGate as createAnonymisationGateEntity } from "@pilotspan/factories/anonymisation-gates";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@pilotspan/tests/shared";
import { ANONYMISATIONGATES_USE_CASES } from "../__factories__/use-cases.js";

describe("SubmitAnonymisationGate", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: AnonymisationGatesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<AnonymisationGatesDDDDependencies>(
      ANONYMISATIONGATES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = createAnonymisationGateEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeSubmitAnonymisationGate, "execute").mockResolvedValue(useCaseResult);

    await submitAnonymisationGate(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeSubmitAnonymisationGate.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
