/**
 * GetAuditPack DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: pilots
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetGraduateAuditPackParams } from "@pilotspan/core/pilots";

export function createGetAuditPackRequest(overrides: Partial<GetGraduateAuditPackParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
