/**
 * CustodianRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: custodians
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CustodianRepository Port
 *
 * DDD: Application port for custodianrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { AssignCustodianInput, AssignCustodianOutput, ListCustodiansInput, ListCustodiansOutput } from "../dto/custodian.dto";
export interface CustodianRepository {
  listCustodians(input: ListCustodiansInput): Promise<ListCustodiansOutput>;
  assignCustodian(input: AssignCustodianInput): Promise<AssignCustodianOutput>;
}

export type { AssignCustodianInput, AssignCustodianOutput, ListCustodiansInput, ListCustodiansOutput } from "../dto/custodian.dto";
