/**
 * QualityIssueRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: custodians
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * QualityIssueRepository Port
 *
 * DDD: Application port for qualityissuerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateQualityIssueInput, CreateQualityIssueOutput, ListQualityIssuesInput, ListQualityIssuesOutput } from "../dto/quality-issue.dto";
export interface QualityIssueRepository {
  listQualityIssues(input: ListQualityIssuesInput): Promise<ListQualityIssuesOutput>;
  createQualityIssue(input: CreateQualityIssueInput): Promise<CreateQualityIssueOutput>;
}

export type { CreateQualityIssueInput, CreateQualityIssueOutput, ListQualityIssuesInput, ListQualityIssuesOutput } from "../dto/quality-issue.dto";
