/**
 * ShadowAiSystem Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: shadow-ai
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/shadow-ai.openapi.types.js";
import { schemas } from "../schemas/shadow-ai.schemas.js";

/**
 * Entity: ShadowAiSystemEntity
 * Description: Represents the ShadowAiSystem domain model.
 * Source: schemas.ShadowAiSystem
 * Type: Domain Entity (API)
 */
export const ShadowAiSystemEntitySchema = schemas.ShadowAiSystem;
export type ShadowAiSystemEntity = components["schemas"]["ShadowAiSystem"];
