/**
 * Admission DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: readiness
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Admission DTOs
 *
 * DDD: Application DTOs for Admission use cases.
 */

import type { DecideReadinessAdmissionParams, DecideReadinessAdmissionRequestInput } from "@pilotspan/core/readiness/types";

export type DecideReadinessAdmissionInput = DecideReadinessAdmissionParams & DecideReadinessAdmissionRequestInput;

export type DecideReadinessAdmissionOutput = {};
