/**
 * ReadinessAssessment DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: readiness
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ReadinessAssessment DTOs
 *
 * DDD: Application DTOs for ReadinessAssessment use cases.
 */

import type { CreateReadinessAssessmentRequestInput, GetReadinessAssessmentParams, ListReadinessAssessmentsParams } from "@pilotspan/core/readiness/types";

export type ListReadinessAssessmentsInput = ListReadinessAssessmentsParams;

export type CreateReadinessAssessmentInput = CreateReadinessAssessmentRequestInput;

export type GetReadinessAssessmentInput = GetReadinessAssessmentParams;

export type ListReadinessAssessmentsOutput = {};

export type CreateReadinessAssessmentOutput = {};

export type GetReadinessAssessmentOutput = {};
