/**
 * Charter Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: pilots
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { CharterEntity } from "@pilotspan/core/pilots/models/index.js";
import { pilotsSchemas } from "@pilotspan/core/pilots";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "plt";

export function createCharter(overrides: Partial<CharterEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    charterId: overrides.charterId ?? `chr_${ulid().toLowerCase()}`,
    objectives: overrides.objectives ?? faker.lorem.word(),
    pilotId: overrides.pilotId ?? `plt_${ulid().toLowerCase()}`,
    sponsorId: overrides.sponsorId ?? faker.string.uuid(),
    status: overrides.status ?? "draft",
    ...overrides,
  };

  return pilotsSchemas.Charter.parse(raw);
}

export function charterBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createCharter(overrides));
}
