/**
 * TalentAssignment Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: talent-assignments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { TalentAssignmentEntity } from "@pilotspan/core/talent-assignments/models/index.js";
import { talentAssignmentsSchemas } from "@pilotspan/core/talent-assignments";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "tal";

export function createTalentAssignment(overrides: Partial<TalentAssignmentEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    assignmentId: overrides.assignmentId ?? `tal_${ulid().toLowerCase()}`,
    personId: overrides.personId ?? faker.string.uuid(),
    pilotId: overrides.pilotId ?? faker.string.uuid(),
    role: overrides.role ?? "data_scientist",
    ...overrides,
  };

  return talentAssignmentsSchemas.TalentAssignment.parse(raw);
}

export function talentAssignmentBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createTalentAssignment(overrides));
}
