/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: talent-assignments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * TalentAssignments Domain Use Cases
 * 
 * List of all use case names for the talent-assignments domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const TALENTASSIGNMENTS_USE_CASES = [
  "executeCreateTalentAssignment",
  "executeGetTalentAssignment",
  "executeListTalentAssignments"
] as const;
