/**
 * ListShadowAiSystem DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: shadow-ai
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListShadowAiSystemsParams } from "@pilotspan/core/shadow-ai";

export function createListShadowAiSystemRequest(overrides: Partial<ListShadowAiSystemsParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
