/**
 * ExecuteRemediateShadowAiSystem - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: shadow-ai
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteRemediateShadowAiSystem Use Case
 *
 * DDD: Application use case for get Remediation.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { RemediateShadowAiSystemInput, RemediateShadowAiSystemOutput } from "../dto/remediation.dto";
import type { ExecutionContextService, IdGeneratorService } from "@pilotspan/services/_shared/index.js";
import type { RemediationRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteRemediateShadowAiSystem {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly remediation: RemediationRepository
  ) {}

  async execute(input: RemediateShadowAiSystemInput): Promise<RemediateShadowAiSystemOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.shaId();

    // All field names extracted from OpenAPI spec: action, linkedPilotId, notes, ownerPersonId
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).systemId) {
      throw new ValidationError("systemId is required");
    }
    const systemId = (input as any).systemId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.remediation.remediateShadowAiSystem({ systemId: systemId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${systemId}`);
    }

    return entity as RemediateShadowAiSystemOutput;
  }
}
