/**
 * RemediationRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: shadow-ai
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RemediationRepository Port
 *
 * DDD: Application port for remediationrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { RemediateShadowAiSystemInput, RemediateShadowAiSystemOutput } from "../dto/remediation.dto";
export interface RemediationRepository {
  remediateShadowAiSystem(input: RemediateShadowAiSystemInput): Promise<RemediateShadowAiSystemOutput>;
}

export type { RemediateShadowAiSystemInput, RemediateShadowAiSystemOutput } from "../dto/remediation.dto";
