/**
 * ShadowAiSystemRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: shadow-ai
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ShadowAiSystemRepository Port
 *
 * DDD: Application port for shadowaisystemrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateShadowAiSystemInput, CreateShadowAiSystemOutput, GetShadowAiSystemInput, GetShadowAiSystemOutput, ListShadowAiSystemsInput, ListShadowAiSystemsOutput } from "../dto/shadow-ai-system.dto";
export interface ShadowAiSystemRepository {
  listShadowAiSystems(input: ListShadowAiSystemsInput): Promise<ListShadowAiSystemsOutput>;
  createShadowAiSystem(input: CreateShadowAiSystemInput): Promise<CreateShadowAiSystemOutput>;
  getShadowAiSystem(input: GetShadowAiSystemInput): Promise<GetShadowAiSystemOutput>;
}

export type { CreateShadowAiSystemInput, CreateShadowAiSystemOutput, GetShadowAiSystemInput, GetShadowAiSystemOutput, ListShadowAiSystemsInput, ListShadowAiSystemsOutput } from "../dto/shadow-ai-system.dto";
