/**
 * TalentAssignment DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: talent-assignments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * TalentAssignment DTOs
 *
 * DDD: Application DTOs for TalentAssignment use cases.
 */

import type { CreateTalentAssignmentRequestInput, GetTalentAssignmentParams, ListTalentAssignmentsParams } from "@pilotspan/core/talent-assignments/types";

export type ListTalentAssignmentsInput = ListTalentAssignmentsParams;

export type CreateTalentAssignmentInput = CreateTalentAssignmentRequestInput;

export type GetTalentAssignmentInput = GetTalentAssignmentParams;

export type ListTalentAssignmentsOutput = {};

export type CreateTalentAssignmentOutput = {};

export type GetTalentAssignmentOutput = {};
