/**
 * Custodian DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: custodians
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Custodian DTOs
 *
 * DDD: Application DTOs for Custodian use cases.
 */

import type { AssignCustodianRequestInput, ListCustodiansParams } from "@pilotspan/core/custodians/types";

export type ListCustodiansInput = ListCustodiansParams;

export type AssignCustodianInput = AssignCustodianRequestInput;

export type ListCustodiansOutput = {};

export type AssignCustodianOutput = {};
