/**
 * ListReadinessAssessment DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: readiness
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListReadinessAssessmentsParams } from "@pilotspan/core/readiness";

export function createListReadinessAssessmentRequest(overrides: Partial<ListReadinessAssessmentsParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
