/**
 * Readiness DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: readiness
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Readiness Domain Module - Composition root
 *
 * DDD: Composition root for readiness domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  AdmissionRepositoryAdapter,
  ReadinessAssessmentRepositoryAdapter,
} from "@pilotspan/adapters/readiness";
import { getIdGeneratorService } from "@pilotspan/adapters";
import type { AdapterDynamoDBClient } from "@pilotspan/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateReadinessAssessment,
  ExecuteDecideReadinessAdmission,
  ExecuteGetReadinessAssessment,
  ExecuteListReadinessAssessments,
} from "@pilotspan/services/readiness/usecases";
// Ports (interfaces)
import type {
  AdmissionRepository,
  ReadinessAssessmentRepository,
} from "@pilotspan/services/readiness/ports";

export interface ReadinessDomainModule {
  repos: {
    admissions: AdmissionRepository;
    assessments: ReadinessAssessmentRepository;
  };
  useCases: {
    admissions: {
      get: ExecuteDecideReadinessAdmission;
    };
    assessments: {
      create: ExecuteCreateReadinessAssessment;
      get: ExecuteGetReadinessAssessment;
      list: ExecuteListReadinessAssessments;
    };
  };
}

export function buildReadinessDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): ReadinessDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      admissions?: AdmissionRepository;
      assessments?: ReadinessAssessmentRepository;
    } = {};

    obj.admissions = new AdmissionRepositoryAdapter(dynamoClient);
    obj.assessments = new ReadinessAssessmentRepositoryAdapter(dynamoClient);
    return {
      admissions: obj.admissions!,
      assessments: obj.assessments!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    admissions: {
      get: new ExecuteDecideReadinessAdmission(executionContext, idGenerator, repos.admissions),
    },
    assessments: {
      create: new ExecuteCreateReadinessAssessment(executionContext, idGenerator, repos.assessments),
      get: new ExecuteGetReadinessAssessment(executionContext, idGenerator, repos.assessments),
      list: new ExecuteListReadinessAssessments(executionContext, idGenerator, repos.assessments),
    },
  };
  return { repos, useCases: useCases as ReadinessDomainModule["useCases"] };
}
