/**
 * TalentAssignment Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: talent-assignments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/talent-assignments.openapi.types.js";
import { schemas } from "../schemas/talent-assignments.schemas.js";

/**
 * Entity: TalentAssignmentEntity
 * Description: Represents the TalentAssignment domain model.
 * Source: schemas.TalentAssignment
 * Type: Domain Entity (API)
 */
export const TalentAssignmentEntitySchema = schemas.TalentAssignment;
export type TalentAssignmentEntity = components["schemas"]["TalentAssignment"];
