/**
 * ListQualityIssues handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: custodians
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listQualityIssues } from "@pilotspan/api-server/domains/custodians/handlers";
import type { CustodiansDDDDependencies } from "@pilotspan/api-server/domains/custodians";
import { createQualityIssue as createQualityIssueEntity } from "@pilotspan/factories/custodians";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@pilotspan/tests/shared";
import { CUSTODIANS_USE_CASES } from "../__factories__/use-cases.js";

describe("ListQualityIssues", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: CustodiansDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<CustodiansDDDDependencies>(
      CUSTODIANS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createQualityIssueEntity({ orgId }),
      createQualityIssueEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListQualityIssues, "execute").mockResolvedValue(useCaseResult);

    await listQualityIssues(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListQualityIssues.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
