/**
 * AdmissionRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: readiness
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AdmissionRepository Port
 *
 * DDD: Application port for admissionrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { DecideReadinessAdmissionInput, DecideReadinessAdmissionOutput } from "../dto/admission.dto";
export interface AdmissionRepository {
  decideReadinessAdmission(input: DecideReadinessAdmissionInput): Promise<DecideReadinessAdmissionOutput>;
}

export type { DecideReadinessAdmissionInput, DecideReadinessAdmissionOutput } from "../dto/admission.dto";
