/**
 * ReadinessAssessment Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: readiness
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { ReadinessAssessmentEntity } from "@pilotspan/core/readiness/models/index.js";
import { readinessSchemas } from "@pilotspan/core/readiness";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "rdy";

export function createReadinessAssessment(overrides: Partial<ReadinessAssessmentEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    admissionStatus: overrides.admissionStatus ?? "draft",
    assessmentId: overrides.assessmentId ?? `rdy_${ulid().toLowerCase()}`,
    dataScore: overrides.dataScore ?? faker.number.int(),
    infrastructureScore: overrides.infrastructureScore ?? faker.number.int(),
    organisationId: overrides.organisationId ?? faker.string.uuid(),
    overallScore: overrides.overallScore ?? faker.number.int(),
    processScore: overrides.processScore ?? faker.number.int(),
    structureScore: overrides.structureScore ?? faker.number.int(),
    talentScore: overrides.talentScore ?? faker.number.int(),
    ...overrides,
  };

  return readinessSchemas.ReadinessAssessment.parse(raw);
}

export function readinessAssessmentBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createReadinessAssessment(overrides));
}
