/**
 * Domains Barrel Export
 *
 * AUTO-GENERATED by codegen (api_server_domain_routes). Do not edit by hand.
 * Centralized exports for all domain dependency builders and types.
 */

// Export all domain dependency builders
export { buildAnonymisationGatesDomainModule } from "./anonymisation-gates/dependencies/anonymisation-gates-ddd.dependencies.js";
export { buildCustodiansDomainModule } from "./custodians/dependencies/custodians-ddd.dependencies.js";
export { buildIdentityDomainModule } from "./identity/dependencies/identity-ddd.dependencies.js";
export { buildPilotsDomainModule } from "./pilots/dependencies/pilots-ddd.dependencies.js";
export { buildReadinessDomainModule } from "./readiness/dependencies/readiness-ddd.dependencies.js";
export { buildShadowAiDomainModule } from "./shadow-ai/dependencies/shadow-ai-ddd.dependencies.js";
export { buildTalentAssignmentsDomainModule } from "./talent-assignments/dependencies/talent-assignments-ddd.dependencies.js";

// Export all domain dependency types
export type { AnonymisationGatesDomainModule } from "./anonymisation-gates/dependencies/anonymisation-gates-ddd.dependencies.js";
export type { CustodiansDomainModule } from "./custodians/dependencies/custodians-ddd.dependencies.js";
export type { IdentityDomainModule } from "./identity/dependencies/identity-ddd.dependencies.js";
export type { PilotsDomainModule } from "./pilots/dependencies/pilots-ddd.dependencies.js";
export type { ReadinessDomainModule } from "./readiness/dependencies/readiness-ddd.dependencies.js";
export type { ShadowAiDomainModule } from "./shadow-ai/dependencies/shadow-ai-ddd.dependencies.js";
export type { TalentAssignmentsDomainModule } from "./talent-assignments/dependencies/talent-assignments-ddd.dependencies.js";
