/**
 * ShadowAiSystem Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: shadow-ai
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { ShadowAiSystemEntity } from "@pilotspan/core/shadow-ai/models/index.js";
import { shadowAiSchemas } from "@pilotspan/core/shadow-ai";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "sha";

export function createShadowAiSystem(overrides: Partial<ShadowAiSystemEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    department: overrides.department ?? faker.lorem.word(),
    discoveredAt: overrides.discoveredAt ?? new Date().toISOString(),
    name: overrides.name ?? faker.person.fullName(),
    status: overrides.status ?? "discovered",
    systemId: overrides.systemId ?? `sha_${ulid().toLowerCase()}`,
    ...overrides,
  };

  return shadowAiSchemas.ShadowAiSystem.parse(raw);
}

export function shadowAiSystemBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createShadowAiSystem(overrides));
}
