/**
 * Repository interface for ReadinessAssessment
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: readiness
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  ReadinessAssessmentEntity
} from "../models/readiness-assessment.entity.js";
import type {
  ListReadinessAssessmentsParams,
  ReadinessAssessment
} from "../types/index.js";
/**
 * ReadinessAssessmentRepository Interface
 */
export interface ReadinessAssessmentRepository extends CreateReadRepository<ReadinessAssessmentEntity, ReadinessAssessment, string, ListReadinessAssessmentsParams> {

}
