/**
 * ExecuteGetAnonymisationGate - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: anonymisation-gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetAnonymisationGate Use Case
 *
 * DDD: Application use case for get AnonymisationGate.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetAnonymisationGateInput, GetAnonymisationGateOutput } from "../dto/anonymisation-gate.dto";
import type { ExecutionContextService, IdGeneratorService } from "@pilotspan/services/_shared/index.js";
import type { AnonymisationGateRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetAnonymisationGate {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly anonymisationGate: AnonymisationGateRepository
  ) {}

  async execute(input: GetAnonymisationGateInput): Promise<GetAnonymisationGateOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.angId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).gateId) {
      throw new ValidationError("gateId is required");
    }
    const gateId = (input as any).gateId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.anonymisationGate.getAnonymisationGate({ gateId: gateId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${gateId}`);
    }

    return entity as GetAnonymisationGateOutput;
  }
}
