/**
 * ExecuteListAnonymisationGates - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: anonymisation-gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListAnonymisationGates Use Case
 *
 * DDD: Application use case for list AnonymisationGate.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListAnonymisationGatesInput, ListAnonymisationGatesOutput } from "../dto/anonymisation-gate.dto";
import type { ExecutionContextService, IdGeneratorService } from "@pilotspan/services/_shared/index.js";
import type { AnonymisationGateRepository } from "../ports";

export class ExecuteListAnonymisationGates {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly anonymisationGate: AnonymisationGateRepository
  ) {}

  async execute(input: ListAnonymisationGatesInput): Promise<ListAnonymisationGatesOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.angId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.anonymisationGate.listAnonymisationGates({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListAnonymisationGatesOutput;
  }
}
