/**
 * ExecuteSubmitAnonymisationGate - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: anonymisation-gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteSubmitAnonymisationGate Use Case
 *
 * DDD: Application use case for create AnonymisationGate.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { SubmitAnonymisationGateInput, SubmitAnonymisationGateOutput } from "../dto/anonymisation-gate.dto";
import type { ExecutionContextService, IdGeneratorService } from "@pilotspan/services/_shared/index.js";
import type { AnonymisationGateRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteSubmitAnonymisationGate {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly anonymisationGate: AnonymisationGateRepository
  ) {}

  async execute(input: SubmitAnonymisationGateInput): Promise<SubmitAnonymisationGateOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.angId();

    // All field names extracted from OpenAPI spec: aggregateScore, correlatedFeatureNotes, groupScore, hashDigestScore, pilotId, removeScore, topBottomCodingScore
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.groupScore) {
      throw new ValidationError("groupScore is required");
    }
    if (!input.topBottomCodingScore) {
      throw new ValidationError("topBottomCodingScore is required");
    }
    if (!input.pilotId) {
      throw new ValidationError("pilotId is required");
    }
    if (!input.aggregateScore) {
      throw new ValidationError("aggregateScore is required");
    }
    if (!input.hashDigestScore) {
      throw new ValidationError("hashDigestScore is required");
    }
    if (!input.removeScore) {
      throw new ValidationError("removeScore is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (anonymisation-gates domain)
    const entityId = this.idGenerator.angId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.anonymisationGate.submitAnonymisationGate({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as SubmitAnonymisationGateOutput;
  }
}
