/**
 * ListAnonymisationGate DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: anonymisation-gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListAnonymisationGatesParams } from "@pilotspan/core/anonymisation-gates";

export function createListAnonymisationGateRequest(overrides: Partial<ListAnonymisationGatesParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
