/**
 * AnonymisationGateRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: anonymisation-gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AnonymisationGateRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements AnonymisationGateRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  AnonymisationGateRepository,
} from "@pilotspan/services/anonymisation-gates";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { AnonymisationGateRepositoryDdb } from "./anonymisation-gate-repository.ddb.js";

/**
 * AnonymisationGateRepositoryAdapter
 *
 * Implements AnonymisationGateRepository port for infrastructure layer.
 */
export class AnonymisationGateRepositoryAdapter implements AnonymisationGateRepository {
  private readonly ddb: AnonymisationGateRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new AnonymisationGateRepositoryDdb(this.dynamoClient);
  }

  async listAnonymisationGates(input: Parameters<AnonymisationGateRepository['listAnonymisationGates']>[0]): Promise<Awaited<ReturnType<AnonymisationGateRepository['listAnonymisationGates']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listAnonymisationGates(input);
  }

  async submitAnonymisationGate(input: Parameters<AnonymisationGateRepository['submitAnonymisationGate']>[0]): Promise<Awaited<ReturnType<AnonymisationGateRepository['submitAnonymisationGate']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.submitAnonymisationGate(input);
  }

  async getAnonymisationGate(input: Parameters<AnonymisationGateRepository['getAnonymisationGate']>[0]): Promise<Awaited<ReturnType<AnonymisationGateRepository['getAnonymisationGate']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getAnonymisationGate(input);
  }
}
