/**
 * DynamoDB repository adapters barrel export
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: anonymisation-gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./anonymisation-gate-repository.ddb.js";
export * from "./decision-repository.ddb.js";
export * from "./anonymisation-gate-repository.adapter.js";
export * from "./decision-repository.adapter.js";
