/**
 * Routes for TalentAssignment
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: talent-assignments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createTalentAssignment, getTalentAssignment, listTalentAssignments } from "../handlers/talent-assignment.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function talentAssignmentRoutes(fastify: FastifyInstance) {
  // POST /v1/talent-assignments (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/talent-assignments",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getTalentAssignmentsDependenciesForRequest();
        await createTalentAssignment(request, reply, deps);
      });
    }
  );


  // GET /v1/talent-assignments (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/talent-assignments",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getTalentAssignmentsDependenciesForRequest();
        await listTalentAssignments(request, reply, deps);
      });
    }
  );


  // GET /v1/talent-assignments/{assignmentId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/talent-assignments/:assignmentId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { assignmentId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getTalentAssignmentsDependenciesForRequest();
        await getTalentAssignment(request, reply, deps);
      });
    }
  );


}
