/**
 * Routes for Admission
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: readiness
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { decideReadinessAdmission } from "../handlers/admission.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function admissionRoutes(fastify: FastifyInstance) {
  // POST /v1/readiness-assessments/{assessmentId}/admission (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/readiness-assessments/:assessmentId/admission",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { assessmentId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getReadinessDependenciesForRequest();
        await decideReadinessAdmission(request, reply, deps);
      });
    }
  );


}
