/**
 * Routes for ReadinessAssessment
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: readiness
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createReadinessAssessment, getReadinessAssessment, listReadinessAssessments } from "../handlers/readiness-assessment.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function readinessAssessmentRoutes(fastify: FastifyInstance) {
  // POST /v1/readiness-assessments (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/readiness-assessments",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getReadinessDependenciesForRequest();
        await createReadinessAssessment(request, reply, deps);
      });
    }
  );


  // GET /v1/readiness-assessments (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/readiness-assessments",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getReadinessDependenciesForRequest();
        await listReadinessAssessments(request, reply, deps);
      });
    }
  );


  // GET /v1/readiness-assessments/{assessmentId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/readiness-assessments/:assessmentId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { assessmentId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getReadinessDependenciesForRequest();
        await getReadinessAssessment(request, reply, deps);
      });
    }
  );


}
