/**
 * AnonymisationGates DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: anonymisation-gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AnonymisationGates Domain Module - Composition root
 *
 * DDD: Composition root for anonymisation-gates domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  AnonymisationGateRepositoryAdapter,
  DecisionRepositoryAdapter,
} from "@pilotspan/adapters/anonymisation-gates";
import { getIdGeneratorService } from "@pilotspan/adapters";
import type { AdapterDynamoDBClient } from "@pilotspan/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteDecideAnonymisationGate,
  ExecuteGetAnonymisationGate,
  ExecuteListAnonymisationGates,
  ExecuteSubmitAnonymisationGate,
} from "@pilotspan/services/anonymisation-gates/usecases";
// Ports (interfaces)
import type {
  AnonymisationGateRepository,
  DecisionRepository,
} from "@pilotspan/services/anonymisation-gates/ports";

export interface AnonymisationGatesDomainModule {
  repos: {
    anonymisationGates: AnonymisationGateRepository;
    decisions: DecisionRepository;
  };
  useCases: {
    anonymisationGates: {
      create: ExecuteSubmitAnonymisationGate;
      get: ExecuteGetAnonymisationGate;
      list: ExecuteListAnonymisationGates;
    };
    decisions: {
      get: ExecuteDecideAnonymisationGate;
    };
  };
}

export function buildAnonymisationGatesDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): AnonymisationGatesDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      anonymisationGates?: AnonymisationGateRepository;
      decisions?: DecisionRepository;
    } = {};

    obj.anonymisationGates = new AnonymisationGateRepositoryAdapter(dynamoClient);
    obj.decisions = new DecisionRepositoryAdapter(dynamoClient);
    return {
      anonymisationGates: obj.anonymisationGates!,
      decisions: obj.decisions!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    anonymisationGates: {
      create: new ExecuteSubmitAnonymisationGate(executionContext, idGenerator, repos.anonymisationGates),
      get: new ExecuteGetAnonymisationGate(executionContext, idGenerator, repos.anonymisationGates),
      list: new ExecuteListAnonymisationGates(executionContext, idGenerator, repos.anonymisationGates),
    },
    decisions: {
      get: new ExecuteDecideAnonymisationGate(executionContext, idGenerator, repos.decisions),
    },
  };
  return { repos, useCases: useCases as AnonymisationGatesDomainModule["useCases"] };
}
