/**
 * Routes for Charter
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: pilots
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getPilotCharter, upsertPilotCharter } from "../handlers/charter.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function charterRoutes(fastify: FastifyInstance) {
  // GET /v1/pilots/{pilotId}/charter (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/pilots/:pilotId/charter",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { pilotId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getPilotsDependenciesForRequest();
        await getPilotCharter(request, reply, deps);
      });
    }
  );


  // PUT /v1/pilots/{pilotId}/charter (unscoped; scope set for security middleware)
  fastify.put(
    "/v1/pilots/:pilotId/charter",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { pilotId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getPilotsDependenciesForRequest();
        await upsertPilotCharter(request, reply, deps);
      });
    }
  );


}
