/**
 * Routes for Decision
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: pilots
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { listPilotDecisions, recordPortfolioDecision } from "../handlers/decision.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function decisionRoutes(fastify: FastifyInstance) {
  // GET /v1/pilots/{pilotId}/decisions (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/pilots/:pilotId/decisions",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { pilotId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getPilotsDependenciesForRequest();
        await listPilotDecisions(request, reply, deps);
      });
    }
  );


  // POST /v1/pilots/{pilotId}/decisions (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/pilots/:pilotId/decisions",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { pilotId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getPilotsDependenciesForRequest();
        await recordPortfolioDecision(request, reply, deps);
      });
    }
  );


}
