/**
 * Handlers for Charter
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: pilots
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { PilotsDomainModule } from "../dependencies/pilots-ddd.dependencies.js";
import type { GetPilotCharterInput, UpsertPilotCharterInput } from "@pilotspan/services/pilots";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/pilots/{pilotId}/charter
 * Operation: getPilotCharter
 */
export async function getPilotCharter(
  request: FastifyRequest<{ Params: { pilotId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: PilotsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetPilotCharterInput = {
    pilotId: request.params.pilotId,
  };
  const result = await deps.useCases.charters.get.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for PUT /v1/pilots/{pilotId}/charter
 * Operation: upsertPilotCharter
 */
export async function upsertPilotCharter(
  request: FastifyRequest<{ Params: { pilotId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: PilotsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: UpsertPilotCharterInput = {
    pilotId: request.params.pilotId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.charters.get.execute(input);
  return reply.code(200).send(result);
}


