/**
 * Handlers for Decision
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: pilots
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { PilotsDomainModule } from "../dependencies/pilots-ddd.dependencies.js";
import type { ListPilotDecisionsInput, RecordPortfolioDecisionInput } from "@pilotspan/services/pilots";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/pilots/{pilotId}/decisions
 * Operation: listPilotDecisions
 */
export async function listPilotDecisions(
  request: FastifyRequest<{ Params: { pilotId: string }; Querystring: { cursor?: string | string[], limit?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: PilotsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListPilotDecisionsInput = {
    pilotId: request.params.pilotId,
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.decisions.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/pilots/{pilotId}/decisions
 * Operation: recordPortfolioDecision
 */
export async function recordPortfolioDecision(
  request: FastifyRequest<{ Params: { pilotId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: PilotsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: RecordPortfolioDecisionInput = {
    pilotId: request.params.pilotId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.decisions.get.execute(input);
  return reply.code(201).send(result);
}


