/**
 * AnonymisationGate Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: anonymisation-gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { AnonymisationGateEntity } from "@pilotspan/core/anonymisation-gates/models/index.js";
import { anonymisationGatesSchemas } from "@pilotspan/core/anonymisation-gates";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "ang";

export function createAnonymisationGate(overrides: Partial<AnonymisationGateEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    aggregateScore: overrides.aggregateScore ?? faker.number.int(),
    gateId: overrides.gateId ?? `ang_${ulid().toLowerCase()}`,
    groupScore: overrides.groupScore ?? faker.number.int(),
    hashDigestScore: overrides.hashDigestScore ?? faker.number.int(),
    passThreshold: overrides.passThreshold ?? faker.number.int(),
    pilotId: overrides.pilotId ?? `plt_${ulid().toLowerCase()}`,
    removeScore: overrides.removeScore ?? faker.number.int(),
    status: overrides.status ?? "submitted",
    topBottomCodingScore: overrides.topBottomCodingScore ?? faker.number.int(),
    totalScore: overrides.totalScore ?? faker.number.int(),
    ...overrides,
  };

  return anonymisationGatesSchemas.AnonymisationGate.parse(raw);
}

export function anonymisationGateBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createAnonymisationGate(overrides));
}
