/**
 * CustodianRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: custodians
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CustodianRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements CustodianRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  CustodianRepository,
} from "@pilotspan/services/custodians";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { CustodianRepositoryDdb } from "./custodian-repository.ddb.js";

/**
 * CustodianRepositoryAdapter
 *
 * Implements CustodianRepository port for infrastructure layer.
 */
export class CustodianRepositoryAdapter implements CustodianRepository {
  private readonly ddb: CustodianRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new CustodianRepositoryDdb(this.dynamoClient);
  }

  async listCustodians(input: Parameters<CustodianRepository['listCustodians']>[0]): Promise<Awaited<ReturnType<CustodianRepository['listCustodians']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listCustodians(input);
  }

  async assignCustodian(input: Parameters<CustodianRepository['assignCustodian']>[0]): Promise<Awaited<ReturnType<CustodianRepository['assignCustodian']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.assignCustodian(input);
  }
}
