/**
 * DynamoDB repository adapters barrel export
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: custodians
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./custodian-repository.ddb.js";
export * from "./dataset-approval-repository.ddb.js";
export * from "./quality-issue-repository.ddb.js";
export * from "./custodian-repository.adapter.js";
export * from "./dataset-approval-repository.adapter.js";
export * from "./quality-issue-repository.adapter.js";
