/**
 * QualityIssueRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: custodians
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * QualityIssueRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements QualityIssueRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  QualityIssueRepository,
} from "@pilotspan/services/custodians";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { QualityIssueRepositoryDdb } from "./quality-issue-repository.ddb.js";

/**
 * QualityIssueRepositoryAdapter
 *
 * Implements QualityIssueRepository port for infrastructure layer.
 */
export class QualityIssueRepositoryAdapter implements QualityIssueRepository {
  private readonly ddb: QualityIssueRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new QualityIssueRepositoryDdb(this.dynamoClient);
  }

  async listQualityIssues(input: Parameters<QualityIssueRepository['listQualityIssues']>[0]): Promise<Awaited<ReturnType<QualityIssueRepository['listQualityIssues']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listQualityIssues(input);
  }

  async createQualityIssue(input: Parameters<QualityIssueRepository['createQualityIssue']>[0]): Promise<Awaited<ReturnType<QualityIssueRepository['createQualityIssue']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createQualityIssue(input);
  }
}
