/**
 * AnonymisationGateRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: anonymisation-gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AnonymisationGateRepository Port
 *
 * DDD: Application port for anonymisationgaterepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetAnonymisationGateInput, GetAnonymisationGateOutput, ListAnonymisationGatesInput, ListAnonymisationGatesOutput, SubmitAnonymisationGateInput, SubmitAnonymisationGateOutput } from "../dto/anonymisation-gate.dto";
export interface AnonymisationGateRepository {
  listAnonymisationGates(input: ListAnonymisationGatesInput): Promise<ListAnonymisationGatesOutput>;
  submitAnonymisationGate(input: SubmitAnonymisationGateInput): Promise<SubmitAnonymisationGateOutput>;
  getAnonymisationGate(input: GetAnonymisationGateInput): Promise<GetAnonymisationGateOutput>;
}

export type { GetAnonymisationGateInput, GetAnonymisationGateOutput, ListAnonymisationGatesInput, ListAnonymisationGatesOutput, SubmitAnonymisationGateInput, SubmitAnonymisationGateOutput } from "../dto/anonymisation-gate.dto";
