/**
 * Custodian Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: custodians
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { CustodianEntity } from "@pilotspan/core/custodians/models/index.js";
import { custodiansSchemas } from "@pilotspan/core/custodians";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "cst";

export function createCustodian(overrides: Partial<CustodianEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    custodianId: overrides.custodianId ?? `cst_${ulid().toLowerCase()}`,
    datasetName: overrides.datasetName ?? faker.lorem.word(),
    personId: overrides.personId ?? faker.string.uuid(),
    ...overrides,
  };

  return custodiansSchemas.Custodian.parse(raw);
}

export function custodianBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createCustodian(overrides));
}
