/**
 * AuditPackRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: pilots
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AuditPackRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements AuditPackRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  AuditPackRepository,
} from "@pilotspan/services/pilots";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { AuditPackRepositoryDdb } from "./audit-pack-repository.ddb.js";

/**
 * AuditPackRepositoryAdapter
 *
 * Implements AuditPackRepository port for infrastructure layer.
 */
export class AuditPackRepositoryAdapter implements AuditPackRepository {
  private readonly ddb: AuditPackRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new AuditPackRepositoryDdb(this.dynamoClient);
  }

  async getGraduateAuditPack(input: Parameters<AuditPackRepository['getGraduateAuditPack']>[0]): Promise<Awaited<ReturnType<AuditPackRepository['getGraduateAuditPack']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getGraduateAuditPack(input);
  }
}
