/**
 * CharterRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: pilots
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CharterRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements CharterRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  CharterRepository,
} from "@pilotspan/services/pilots";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { CharterRepositoryDdb } from "./charter-repository.ddb.js";

/**
 * CharterRepositoryAdapter
 *
 * Implements CharterRepository port for infrastructure layer.
 */
export class CharterRepositoryAdapter implements CharterRepository {
  private readonly ddb: CharterRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new CharterRepositoryDdb(this.dynamoClient);
  }

  async getPilotCharter(input: Parameters<CharterRepository['getPilotCharter']>[0]): Promise<Awaited<ReturnType<CharterRepository['getPilotCharter']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getPilotCharter(input);
  }

  async upsertPilotCharter(input: Parameters<CharterRepository['upsertPilotCharter']>[0]): Promise<Awaited<ReturnType<CharterRepository['upsertPilotCharter']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.upsertPilotCharter(input);
  }
}
