/**
 * Pilot Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: pilots
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { PilotEntity } from "@pilotspan/core/pilots/models/index.js";
import { pilotsSchemas } from "@pilotspan/core/pilots";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "plt";

export function createPilot(overrides: Partial<PilotEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    name: overrides.name ?? faker.person.fullName(),
    pilotId: overrides.pilotId ?? `plt_${ulid().toLowerCase()}`,
    sponsorId: overrides.sponsorId ?? faker.string.uuid(),
    status: overrides.status ?? "proposed",
    successMetric: overrides.successMetric ?? faker.lorem.word(),
    ...overrides,
  };

  return pilotsSchemas.Pilot.parse(raw);
}

export function pilotBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createPilot(overrides));
}
