/**
 * Custodian Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: custodians
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/custodians.openapi.types.js";
import { schemas } from "../schemas/custodians.schemas.js";

/**
 * Entity: CustodianEntity
 * Description: Represents the Custodian domain model.
 * Source: schemas.Custodian
 * Type: Domain Entity (API)
 */
export const CustodianEntitySchema = schemas.Custodian;
export type CustodianEntity = components["schemas"]["Custodian"];
