/**
 * QualityIssue Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: custodians
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/custodians.openapi.types.js";
import { schemas } from "../schemas/custodians.schemas.js";

/**
 * Entity: QualityIssueEntity
 * Description: Represents the QualityIssue domain model.
 * Source: schemas.QualityIssue
 * Type: Domain Entity (API)
 */
export const QualityIssueEntitySchema = schemas.QualityIssue;
export type QualityIssueEntity = components["schemas"]["QualityIssue"];
