/**
 * TalentAssignmentRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: talent-assignments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * TalentAssignmentRepository Port
 *
 * DDD: Application port for talentassignmentrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateTalentAssignmentInput, CreateTalentAssignmentOutput, GetTalentAssignmentInput, GetTalentAssignmentOutput, ListTalentAssignmentsInput, ListTalentAssignmentsOutput } from "../dto/talent-assignment.dto";
export interface TalentAssignmentRepository {
  listTalentAssignments(input: ListTalentAssignmentsInput): Promise<ListTalentAssignmentsOutput>;
  createTalentAssignment(input: CreateTalentAssignmentInput): Promise<CreateTalentAssignmentOutput>;
  getTalentAssignment(input: GetTalentAssignmentInput): Promise<GetTalentAssignmentOutput>;
}

export type { CreateTalentAssignmentInput, CreateTalentAssignmentOutput, GetTalentAssignmentInput, GetTalentAssignmentOutput, ListTalentAssignmentsInput, ListTalentAssignmentsOutput } from "../dto/talent-assignment.dto";
