/**
 * ExecuteGetTalentAssignment - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: talent-assignments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetTalentAssignment Use Case
 *
 * DDD: Application use case for get TalentAssignment.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetTalentAssignmentInput, GetTalentAssignmentOutput } from "../dto/talent-assignment.dto";
import type { ExecutionContextService, IdGeneratorService } from "@pilotspan/services/_shared/index.js";
import type { TalentAssignmentRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetTalentAssignment {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly talentAssignment: TalentAssignmentRepository
  ) {}

  async execute(input: GetTalentAssignmentInput): Promise<GetTalentAssignmentOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.talId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).assignmentId) {
      throw new ValidationError("assignmentId is required");
    }
    const assignmentId = (input as any).assignmentId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.talentAssignment.getTalentAssignment({ assignmentId: assignmentId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${assignmentId}`);
    }

    return entity as GetTalentAssignmentOutput;
  }
}
