/**
 * ExecuteCreateTalentAssignment - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: talent-assignments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateTalentAssignment Use Case
 *
 * DDD: Application use case for create TalentAssignment.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateTalentAssignmentInput, CreateTalentAssignmentOutput } from "../dto/talent-assignment.dto";
import type { ExecutionContextService, IdGeneratorService } from "@pilotspan/services/_shared/index.js";
import type { TalentAssignmentRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateTalentAssignment {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly talentAssignment: TalentAssignmentRepository
  ) {}

  async execute(input: CreateTalentAssignmentInput): Promise<CreateTalentAssignmentOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.talId();

    // All field names extracted from OpenAPI spec: domainConsultBookedAt, hoursCommitted, personId, pilotId, role
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.pilotId) {
      throw new ValidationError("pilotId is required");
    }
    if (!input.role) {
      throw new ValidationError("role is required");
    }
    if (!input.personId) {
      throw new ValidationError("personId is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (talent-assignments domain)
    const entityId = this.idGenerator.talId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.talentAssignment.createTalentAssignment({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateTalentAssignmentOutput;
  }
}
