/**
 * Custodians DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: custodians
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Custodians Domain Module - Composition root
 *
 * DDD: Composition root for custodians domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  CustodianRepositoryAdapter,
  DatasetApprovalRepositoryAdapter,
  QualityIssueRepositoryAdapter,
} from "@pilotspan/adapters/custodians";
import { getIdGeneratorService } from "@pilotspan/adapters";
import type { AdapterDynamoDBClient } from "@pilotspan/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteAssignCustodian,
  ExecuteCreateQualityIssue,
  ExecuteDecideDatasetApproval,
  ExecuteListCustodians,
  ExecuteListDatasetApprovals,
  ExecuteListQualityIssues,
} from "@pilotspan/services/custodians/usecases";
// Ports (interfaces)
import type {
  CustodianRepository,
  DatasetApprovalRepository,
  QualityIssueRepository,
} from "@pilotspan/services/custodians/ports";

export interface CustodiansDomainModule {
  repos: {
    custodians: CustodianRepository;
    datasetApprovals: DatasetApprovalRepository;
    qualityIssues: QualityIssueRepository;
  };
  useCases: {
    custodians: {
      get: ExecuteAssignCustodian;
      list: ExecuteListCustodians;
    };
    datasetApprovals: {
      get: ExecuteDecideDatasetApproval;
      list: ExecuteListDatasetApprovals;
    };
    qualityIssues: {
      create: ExecuteCreateQualityIssue;
      list: ExecuteListQualityIssues;
    };
  };
}

export function buildCustodiansDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): CustodiansDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      custodians?: CustodianRepository;
      datasetApprovals?: DatasetApprovalRepository;
      qualityIssues?: QualityIssueRepository;
    } = {};

    obj.custodians = new CustodianRepositoryAdapter(dynamoClient);
    obj.datasetApprovals = new DatasetApprovalRepositoryAdapter(dynamoClient);
    obj.qualityIssues = new QualityIssueRepositoryAdapter(dynamoClient);
    return {
      custodians: obj.custodians!,
      datasetApprovals: obj.datasetApprovals!,
      qualityIssues: obj.qualityIssues!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    custodians: {
      get: new ExecuteAssignCustodian(executionContext, idGenerator, repos.custodians),
      list: new ExecuteListCustodians(executionContext, idGenerator, repos.custodians),
    },
    datasetApprovals: {
      get: new ExecuteDecideDatasetApproval(executionContext, idGenerator, repos.datasetApprovals),
      list: new ExecuteListDatasetApprovals(executionContext, idGenerator, repos.datasetApprovals),
    },
    qualityIssues: {
      create: new ExecuteCreateQualityIssue(executionContext, idGenerator, repos.qualityIssues),
      list: new ExecuteListQualityIssues(executionContext, idGenerator, repos.qualityIssues),
    },
  };
  return { repos, useCases: useCases as CustodiansDomainModule["useCases"] };
}
