/**
 * TalentAssignmentRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: talent-assignments
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * TalentAssignmentRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements TalentAssignmentRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  TalentAssignmentRepository,
} from "@pilotspan/services/talent-assignments";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { TalentAssignmentRepositoryDdb } from "./talent-assignment-repository.ddb.js";

/**
 * TalentAssignmentRepositoryAdapter
 *
 * Implements TalentAssignmentRepository port for infrastructure layer.
 */
export class TalentAssignmentRepositoryAdapter implements TalentAssignmentRepository {
  private readonly ddb: TalentAssignmentRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new TalentAssignmentRepositoryDdb(this.dynamoClient);
  }

  async listTalentAssignments(input: Parameters<TalentAssignmentRepository['listTalentAssignments']>[0]): Promise<Awaited<ReturnType<TalentAssignmentRepository['listTalentAssignments']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listTalentAssignments(input);
  }

  async createTalentAssignment(input: Parameters<TalentAssignmentRepository['createTalentAssignment']>[0]): Promise<Awaited<ReturnType<TalentAssignmentRepository['createTalentAssignment']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createTalentAssignment(input);
  }

  async getTalentAssignment(input: Parameters<TalentAssignmentRepository['getTalentAssignment']>[0]): Promise<Awaited<ReturnType<TalentAssignmentRepository['getTalentAssignment']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getTalentAssignment(input);
  }
}
