/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: shadow-ai
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * ShadowAi Domain Use Cases
 * 
 * List of all use case names for the shadow-ai domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const SHADOWAI_USE_CASES = [
  "executeCreateShadowAiSystem",
  "executeGetShadowAiSystem",
  "executeListShadowAiSystems",
  "executeRemediateShadowAiSystem"
] as const;
