/**
 * ListReadinessAssessments handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: readiness
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listReadinessAssessments } from "@pilotspan/api-server/domains/readiness/handlers";
import type { ReadinessDDDDependencies } from "@pilotspan/api-server/domains/readiness";
import { createReadinessAssessment as createReadinessAssessmentEntity } from "@pilotspan/factories/readiness";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@pilotspan/tests/shared";
import { READINESS_USE_CASES } from "../__factories__/use-cases.js";

describe("ListReadinessAssessments", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ReadinessDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ReadinessDDDDependencies>(
      READINESS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createReadinessAssessmentEntity({ orgId }),
      createReadinessAssessmentEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListReadinessAssessments, "execute").mockResolvedValue(useCaseResult);

    await listReadinessAssessments(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListReadinessAssessments.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
