/**
 * AnonymisationGate Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: anonymisation-gates
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/anonymisation-gates.openapi.types.js";
import { schemas } from "../schemas/anonymisation-gates.schemas.js";

/**
 * Entity: AnonymisationGateEntity
 * Description: Represents the AnonymisationGate domain model.
 * Source: schemas.AnonymisationGate
 * Type: Domain Entity (API)
 */
export const AnonymisationGateEntitySchema = schemas.AnonymisationGate;
export type AnonymisationGateEntity = components["schemas"]["AnonymisationGate"];
