/**
 * Remediation DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: shadow-ai
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Remediation DTOs
 *
 * DDD: Application DTOs for Remediation use cases.
 */

import type { RemediateShadowAiSystemParams, RemediateShadowAiSystemRequestInput } from "@pilotspan/core/shadow-ai/types";

export type RemediateShadowAiSystemInput = RemediateShadowAiSystemParams & RemediateShadowAiSystemRequestInput;

export type RemediateShadowAiSystemOutput = {};
