/**
 * ShadowAiSystem DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: shadow-ai
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ShadowAiSystem DTOs
 *
 * DDD: Application DTOs for ShadowAiSystem use cases.
 */

import type { CreateShadowAiSystemRequestInput, GetShadowAiSystemParams, ListShadowAiSystemsParams } from "@pilotspan/core/shadow-ai/types";

export type ListShadowAiSystemsInput = ListShadowAiSystemsParams;

export type CreateShadowAiSystemInput = CreateShadowAiSystemRequestInput;

export type GetShadowAiSystemInput = GetShadowAiSystemParams;

export type ListShadowAiSystemsOutput = {};

export type CreateShadowAiSystemOutput = {};

export type GetShadowAiSystemOutput = {};
