/**
 * Charter Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: pilots
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/pilots.openapi.types.js";
import { schemas } from "../schemas/pilots.schemas.js";

/**
 * Entity: CharterEntity
 * Description: Represents the Charter domain model.
 * Source: schemas.Charter
 * Type: Domain Entity (API)
 */
export const CharterEntitySchema = schemas.Charter;
export type CharterEntity = components["schemas"]["Charter"];
