/**
 * ExecuteDecideReadinessAdmission - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: readiness
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteDecideReadinessAdmission Use Case
 *
 * DDD: Application use case for get Admission.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { DecideReadinessAdmissionInput, DecideReadinessAdmissionOutput } from "../dto/admission.dto";
import type { ExecutionContextService, IdGeneratorService } from "@pilotspan/services/_shared/index.js";
import type { AdmissionRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteDecideReadinessAdmission {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly admission: AdmissionRepository
  ) {}

  async execute(input: DecideReadinessAdmissionInput): Promise<DecideReadinessAdmissionOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.rdyId();

    // All field names extracted from OpenAPI spec: decision, rationale
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).assessmentId) {
      throw new ValidationError("assessmentId is required");
    }
    const assessmentId = (input as any).assessmentId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.admission.decideReadinessAdmission({ assessmentId: assessmentId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${assessmentId}`);
    }

    return entity as DecideReadinessAdmissionOutput;
  }
}
