/**
 * ReadinessAssessment Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: readiness
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/readiness.openapi.types.js";
import { schemas } from "../schemas/readiness.schemas.js";

/**
 * Entity: ReadinessAssessmentEntity
 * Description: Represents the ReadinessAssessment domain model.
 * Source: schemas.ReadinessAssessment
 * Type: Domain Entity (API)
 */
export const ReadinessAssessmentEntitySchema = schemas.ReadinessAssessment;
export type ReadinessAssessmentEntity = components["schemas"]["ReadinessAssessment"];
